name: Hello, First Action!
description: Greet the nice ones

inputs:
  who-to-greet:
    description: The good ones to greet
    required: true
    default: World

outputs:
  time:
    description: The time we greeted a good one

runs:
  using: docker
  image: Dockerfile
  env:
    INPUT_WHO_TO_GREET: ${{ inputs.who-to-greet }}
